### ISSUE TITLE
Missing Style Sheet Asset

### ISSUE THREAD

**Issue by philsinatra** [jel99/idm221-jl#3]
You have a [reference to `/css/master.css`](https://github.com/jel99/idm221-jl/blob/6956b7fd35eaaac66fc9bf068cc14d3aa1be535b/website/home.html#L19), but that file is not included in your project directory structure. Currently the reference to that file throws an error.

**Comment by jel99** [comment]
This was a mistake... it was a placeholder until I figured out how to link a Javascript file (script.js).
