### ISSUE TITLE
Universal Border Styles

### ISSUE THREAD

**Issue by philsinatra** [jel99/idm221-jl#6]
[Universal border styles](https://github.com/jel99/idm221-jl/blob/6956b7fd35eaaac66fc9bf068cc14d3aa1be535b/website/main.css#L2-L4) are not needed. 

By setting this you're actually prepping that in the remainder of your document all borders should automatically be solid/black by default, which could end up being more work in the long run. No need for the universal selector and border styles in your stylesheet at this point.

**Comment by jel99** [comment]
Ah, yes, I never intended to use those. I only was using it to see where all objects are, sort of how you showed us the pieces of the ESPN site.
